### ISSUE TITLE
Collection of bugs

### ISSUE THREAD

**Issue by parfa30** [desihub/desiperf#20]
* Fix positioner data and plots. Positioner 595 doesn't work; OFFSET_FINAL not in file
 * airmass, air_temp_diff, wind_speed not in data
* Guiding and tput plots not changing with options
* Detector Noise data issue with CAMERA_TEMP

**Comment by paulmartini** [comment]
Hi @parfa30 - I think it will be easier to track (and squash) the bugs if each is a separate issue. What do you think?

**Comment by parfa30** [comment]
Yes, I'm good with that! I was hoping to take care of a bunch all at once but haven't yet so better to have individual issues for each.
