### ISSUE TITLE
Spectral trace coordinates and wavelength calibration vs. environmental parameters

### ISSUE THREAD

**Issue by paulmartini** [desihub/desiperf#22]
Include dx (trace shift) and dy (shift in wavelength direction) from each camera for each spectroscopic exposure. This is to enable studies of changes in where the spectra are dispersed on the detector vs. environmental conditions, especially in the Shack. Note this is motivated by Julien'Guy's discovery of a correlation between trace shift and Shack humidity in the blue and red cameras.

**Comment by paulmartini** [comment]
Hi @parfa30, I looked at the app and I can't figure out how to reproduce Julien's result. I think I understand that on the Spectrograph Page I should choose Spectrograph and Camera for the Categories, and then I think you said on the telecon today that I'd then compare attributes like blue_camera_humidity_mean vs. MEANDX or MEANDY. Is that right? Yet Julien compared the trace shifts to the Shack telemetry, which do not look like they are an option. This is the telemetry from the Shack Controller, such as the Shack air temperature, humidity, overpressure, etc. . Do you include them and I missed it? If they aren't there, I think it would make sense to add "Shack" as an option for the Category menus on the Spectrograph Page. What do you think?

**Comment by parfa30** [comment]
THat's a good point. I know that the Shack data was there before, but might have been lost in the new attribute scramble. I will make sure they are added back.
