### ISSUE TITLE
Spectrograph Page Cleanup

### ISSUE THREAD

**Issue by paulmartini** [desihub/desiperf#46]
On the Spectrograph page, when the Category is "Spectrograph" I think it does not make sense to have the attribute be specific to an individual camera (although I know that is the way the data are stored). For example, if I set "X Category" to Observation and "Y Category" to Spectrograph and then choose to plot EXPID vs. humidity, I have to set the Y Attribute to "nir_camera_humidity_mean" for all three plots. I think it would be more useful to have 'camera_humidity' and 'camera_temp' and then plot the nir_camera_humidity_mean in the "NIR Detectors" panel, red_camera_humidity_mean in the "Red Detectors" panel, etc. At least I can't forsee wanting to plot nir_camera_humidity_mean vs. properties of the other two cameras. 

Note that this isn't true for all attributes under the "Spectrograph" category. The bench temps (and ieb temp) are not specific to cameras.

**Comment by parfa30** [comment]
This makes sense. I think it's how I had it before and have some code in there to do this already, just need to make it work again.
