### ISSUE TITLE
Can't start up the application

### ISSUE THREAD

**Issue by apaat** [desihub/desiperf#50]
When I run ' _bokeh serve --show .\instperfapp\_ ' I receive the following error in the terminal:

2020-10-01 13:57:26,469 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x0000022789545DA0>: cannot convert float NaN to integer
File "main.py", line 60, in data_text:
fp = ['FocalPlane Data', int(min(fps.NIGHT)), int(max(fps.NIGHT)), int(min(fps.EXPID)), int(max(fps.EXPID))] Traceback (most recent call last):
  File "C:\Users\socce\Anaconda3\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\Users\socce\Desktop\KPNO\DESI\desiperf\py\desiperf\instperfapp\main.py", line 84, in <module>
    df = data_text(ds, fps)
  File "C:\Users\socce\Desktop\KPNO\DESI\desiperf\py\desiperf\instperfapp\main.py", line 60, in data_text
    fp = ['FocalPlane Data', int(min(fps.NIGHT)), int(max(fps.NIGHT)), int(min(fps.EXPID)), int(max(fps.EXPID))]
ValueError: cannot convert float NaN to integer

so either fps.NIGHT or fps.EXPID has a NaN, but I don't know how we want to handle them.

**Comment by paulmartini** [comment]
Hi @apaat - I just tried to run the app and did not encounter this error, at least upon startup. Could you check that you are using the latest version? Or let me know if you attempted to make a specific plot prior to seeing this message.

**Comment by apaat** [comment]
Hey @paulmartini, as far as I can tell I am running on the latest version.

I get the error message on the page start up, so I don't even have a chance to make a plot

**Comment by apaat** [comment]
Hi @paulmartini and @parfa30 , I think I have tracked down my problem to the 'fpa_data' files. In the ones that I have checked the 'expid' column is mostly empty, which is what is giving us the NaN's when we try to run 'fps.EXPID' in the main.py.

**Comment by paulmartini** [comment]
Hi @apaat - That is odd. I checked all of the fpa_data_?.csv files and none of them have EXPID = 0. You can check against the repository, e.g. https://github.com/desihub/desiperf/blob/master/py/desiperf/instperfapp/data/focalplane/fp_data_0.csv

**Comment by apaat** [comment]
Hey @paulmartini , looking at it again, I notice two columns in the fpa_data_#.csv files with similar names. The first column is 'EXPID,' and the 47th column is 'expid.' Looking at the lower case 'expid' column is what I noticed before. 

The fps.EXPID values I am seeing match the lower case column rather than the upper case column.

I think the problem for me lies in data_handler.py, on line 34, fp_df.columns = [x.upper() for x in fp_df.columns], which converts lowercase letters to uppercase ones. This is overwriting the first EXPID column (uppercase) with the second (lowercase).

Although none of this explains why I see this problem and you don't

**Comment by paulmartini** [comment]
Hi @apaat - I think I see why there is a column named EXPID and another named expid. In get_fp_data.py, the routine get_exp_df() renames 'id' as 'EXPID', and there is also a routine get_guider_df() that queries for 'expid' when it gets the guider data, and it uses 'expid' to merge data from the guider_summary table and the guider_centroids table. It looks like the code is supposed to drop duplicate columns, but it is not doing so, perhaps because of the upper/lower case difference. It also appears the second 'expid' column has dtype='float64'

**Comment by apaat** [comment]
Hi @paulmartini , if the part of the code to drop duplicates you are referring to is line 82 in get_fp_data.py :
        gs_df_final.drop_duplicates(subset=['EXPID'], keep='first', inplace=True)
, I believe drop_duplicates is case sensitive so it will never merge 'EXPID' and 'expid'.

There are a few things I want to try but I'm not too familiar with this part of the code, so I may just have to wait for @parfa30 .

**Comment by apaat** [comment]
hi @paulmartini , actually looking closer drop_duplicates doesn't remove columns with the same name, it removes duplicate rows

**Comment by apaat** [comment]
Hi @paulmartini , I have found a solution. Adding the line:

        fp_df = fp_df.loc[:,~fp_df.columns.duplicated()]

underneath the line:

        fp_df.columns = [x.upper() for x in fp_df.columns]

in data_handler.py.

This will remove columns with duplicate names, leaving the original. With this I am able to run the code successfully
