### ISSUE TITLE
Focus Attribute

### ISSUE THREAD

**Issue by apaat** [desihub/desiperf#69]
I noticed that the Focus attribute (under the Observation catagory) can not be plotted. Each datapoint for Focus looks to be a list of 6 values (for example here is the first data point [1136.6, -358.0, 718.5, -7.0, 20.0, 173.6]). If we want to be able to plot the Focus we will need to split this up, which is doable but I don't know what any of the individual values mean, so I don't know which one to take. 
Or should we plot all six separately?

**Comment by parfa30** [comment]
Nice catch. We should plot each individually but we should separate them in the data building phase. I'll look into the appropriate names for these 6 entities and let you know what they are

**Comment by apaat** [comment]
Split the FOCUS attribute into its six component parts named FOCUS0 through FOCUS5. When I hear about a naming convention I will name the attributes appropriately
